### ISSUE TITLE
Touchbar command palette not shown up anymore 

### ISSUE THREAD

**Issue by chrisduong** [NascHQ/nasc-vscode-mac-touchbar#13]
Hi,

After several update of **vscode**, A lot of toucbar buttions have gone missing, like command palette, "go to definition",...Only Next/Previous and "Run" are shown up.

**Comment by chrisduong** [comment]
Yes, I think the new version of this extension had add some default **buttons**, which outgrow to not be fit in my touchbar.

I removed one button, then "all buttons" shows up again.

Is it possible to prevent this issue. Could we fix the number of buttons to be fit in touchbar. Any extra buttons will be ignore.

Thanks

**Comment by felipenmoura** [comment]
Good point.
Perhaps, we could add some alert or message when there are too many buttons to show.
We still have to figure out how to do that, thought.
