### ISSUE TITLE
Stop working

### ISSUE THREAD

**Issue by brightsider** [NascHQ/nasc-vscode-mac-touchbar#28]
Hello.
It's stop working on version 1.31.1.

**Comment by felipenmoura** [comment]
Hi @brightsider 
We already published a fix for that, try updating the extension and let me know if it works for ya

**Comment by brightsider** [comment]
Hi @felipenmoura 
I'm already using latest version

**Comment by felipenmoura** [comment]
hm, weird.
I'm using 1.31.0 and it does not offers me any update for the vscode!

Try going to the settings and disabling one of the icons. Some times, the whole bar disappears just because it cannot fit there due to too many icons.

**Comment by brightsider** [comment]
@felipenmoura thank you. It's help.

**Comment by felipenmoura** [comment]
awesome, thanks for using it and let me know of any hard times
