### ISSUE TITLE
Buttons disappear in debug mode 

### ISSUE THREAD

**Issue by jascodes** [NascHQ/nasc-vscode-mac-touchbar#37]
Hey @felipenmoura 
Awesome work on this!!! 🥳 

I work in flutter in hot reload mode. This means I am always in debug mode while in development. I don't see any touch buttons in dubug mode. Is it by design? Can we do something about it.

Thanks

**Comment by felipenmoura** [comment]
Hi @jascodes 
Yup...these buttons are "cropped" away when they don't feet in the bar!
Try disabling one or two buttons and see if the bar reappears to you :)

**Comment by jascodes** [comment]
No see the attached image

When debugger not attached its working
![image](https://user-images.githubusercontent.com/1231593/71589668-ab9dab80-2b4b-11ea-8032-9b1a93310628.jpg)

But when debugger is attached buttons disappear 
![image](https://user-images.githubusercontent.com/1231593/71589709-dab41d00-2b4b-11ea-8b2e-5b87f804fc61.jpg)


Thx

**Comment by jascodes** [comment]
Was due to flutter https://github.com/Dart-Code/Dart-Code/issues/2195

**Comment by felipenmoura** [comment]
Oh, I see!
Thanks for posting it here @jascodes
