### ISSUE TITLE
doesn't show any button

### ISSUE THREAD

**Issue by primalmotion** [NascHQ/nasc-vscode-mac-touchbar#6]
I'm sorry I don't have any more meaningful thing to say, but it just doesn't work for me. I don't see anything in my touch bar. I've tried various other (less cool) touch bar plugins, and they all show buttons in the touch bar, but this extension does not. I don't see any error, no warning, nothing.

I would be happy to provide any additional info you need. 

My VSCode version is `1.18.0`

**Comment by felipenmoura** [comment]
Hi.
Hm, I have seen this happening when you have "too many" buttons.
The VSCode API for the touchbar is very limited, and it looks like when you have more than 6 buttons enabled, it breaks the touchbar layout, going "offscreen", or in this case, "offbar".
Try updating your settings and enable only a couple buttons, see if the appear:

`cmd+, > filter by "nasc" > set as false some buttons`

Please let me know if it works!

**Comment by primalmotion** [comment]
Hi,

I just tried just with one button, and it works. It seems that the debugger button (that I'm not sure if I can remove them) count in the total of 6.

Thanks!

**Comment by felipenmoura** [comment]
hm, maybe when your debugging (because it enables some extra buttons).
I am currently using the touchbar like this 
<img width="1085" alt="touch bar shot 2017-11-29 at 14 39 59" src="https://user-images.githubusercontent.com/347387/33386918-37f62f58-d513-11e7-8306-2b609bff0007.png">

**Comment by primalmotion** [comment]
it's weird, because my default buttons (< > and Play) are huge compared to yours

![img_0083](https://user-images.githubusercontent.com/208711/33396314-00a76500-d4fd-11e7-9e11-63d20feb7122.jpeg)

**Comment by felipenmoura** [comment]
weird indeed! I have no idea why those buttons would be like that! Seems like a bug in the default VSCode buttons!
Leave a comment about it in this issue:
https://github.com/Microsoft/vscode/issues/35641
