### ISSUE TITLE
Debugger support

### ISSUE THREAD

**Issue by mrsimpson** [NascHQ/nasc-vscode-mac-touchbar#8]
The actual thing that really really really such with respect to touchbar is that debugger commands actually always reside on the F-keys. Particularly if you cannot change the keymap.

Adding an icon set which - ideally - is automatically activated once activating the debugger was brilliant!

**Comment by mrsimpson** [comment]
just seen that in the current version vscode provides those icons on its own :+1:

**Comment by felipenmoura** [comment]
Yes, indeed
:+1:
